### ISSUE TITLE
Not compatible with laravel v11

### ISSUE THREAD

**Issue by miomech** [afatmustafa/filamentv3-turnstile#1]
### What happened?

Hi there, This plugin does not work with laravel 11.

### How to reproduce the bug

When attempting to install into laravel 11 composer throws out dependency issue

### Package Version

1.0.0

### PHP Version

8.3

### Laravel Version

11

### Which operating systems does with happen with?

Linux

**Comment by afatmustafa** [comment]
Hi @miomech, this package uses the coderflex/laravel-turnstile package under the hood. I will update to L11 as soon as that package is updated.

**Comment by DariusIII** [comment]
@afatmustafa coderflex/laravel-turnstile has been updated 2 weeks ago to support Laravel 11, can we have an update?

I have created a PR: https://github.com/afatmustafa/filamentv3-turnstile/pull/2

**Comment by afatmustafa** [comment]
I didn't see it, thanks for the PR.

**Comment by DariusIII** [comment]
@afatmustafa When can we expect new version to be tagged?

**Comment by afatmustafa** [comment]
Sorry, I'm having a really busy work period, I just tagged it now.

**Comment by miomech** [comment]
@afatmustafa @DariusIII Thanks for taking care of this!
